/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorusingjava;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        btndot = new javax.swing.JButton();
        btnc = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnSub1 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btndiv1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnoff = new javax.swing.JButton();
        btnon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Simple Calculator by Dawood Shaikh");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        txtInput.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jPanel1.add(txtInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 390, 100));

        btndot.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btndot.setText(".");
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });
        jPanel1.add(btndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 70, 70));

        btnc.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnc.setText("C");
        btnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActionPerformed(evt);
            }
        });
        jPanel1.add(btnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 70, 70));

        btn0.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 70, 70));

        btn3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 70, 70));

        btn2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 70, 70));

        btn1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 70, 70));

        btn4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, 70));

        btn6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 70, 70));

        btn5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, 70));

        btn7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 70, 70));

        btndiv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btndiv.setText("del");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });
        jPanel1.add(btndiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 70, 70));

        btn8.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 70, 70));

        btnequal.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnequal.setText("=");
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });
        jPanel1.add(btnequal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 150, 70));

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnAdd.setText("+");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 256, 80, 130));

        btnMul.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });
        jPanel1.add(btnMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 70, 60));

        btnSub1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnSub1.setText("-");
        btnSub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSub1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 316, 70, 70));

        btn10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn10.setText("9");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 70, 70));

        btndiv1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btndiv1.setText("/");
        btndiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiv1ActionPerformed(evt);
            }
        });
        jPanel1.add(btndiv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 70, 70));

        jLabel2.setText("Model No: DS-001");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 20));

        btnoff.setText("OFF");
        btnoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoffActionPerformed(evt);
            }
        });
        jPanel1.add(btnoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 70, -1));

        btnon.setText("ON");
        btnon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnonActionPerformed(evt);
            }
        });
        jPanel1.add(btnon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, -1));

        jLabel3.setText("Power Mode:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        int len = text.length();
        text= text.substring(0, len-1);
        txtInput.setText(text);
        txtInput.grabFocus();
    }//GEN-LAST:event_btndivActionPerformed

    private void btncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActionPerformed
        // TODO add your handling code here:
        txtInput.setText("");
        txtInput.grabFocus();
    }//GEN-LAST:event_btncActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
       String text = txtInput.getText();
        txtInput.setText(text+"1");
        txtInput.grabFocus();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
       String text = txtInput.getText();
        txtInput.setText(text+"2");
        txtInput.grabFocus();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
       String text = txtInput.getText();
        txtInput.setText(text+"3");
        
        txtInput.grabFocus();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        txtInput.setText(text+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        txtInput.setText(text+".");
    }//GEN-LAST:event_btndotActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        txtInput.setText(text+"4");
        
        txtInput.grabFocus();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        txtInput.setText(text+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        txtInput.setText(text+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        txtInput.setText(text+"7");
        txtInput.grabFocus();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        String text = txtInput.getText();
        boolean flag=true;
        for(int i=0; i<text.length(); i++)
        {
            if(text.charAt(i) == '*' ||text.charAt(i) == '-' || text.charAt(i) == '/' || text.charAt(i) == '+')
            {JOptionPane.showMessageDialog(this, "Only 1 operator is allowed!");
            flag = false;
            break;
            }
        }
        if(flag == true)
            txtInput.setText(text+'+');
       
        txtInput.grabFocus();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSub1ActionPerformed
        // TODO add your handling code here:
      String text = txtInput.getText();
        boolean flag=true;
        for(int i=0; i<text.length(); i++)
        {
            if(text.charAt(i) == '*' ||text.charAt(i) == '-' || text.charAt(i) == '/' || text.charAt(i) == '+')
            {JOptionPane.showMessageDialog(this, "Only 1 operator is allowed!");
            flag = false;
            break;
            }
        }
        if(flag == true)
            txtInput.setText(text+'-');
       
        txtInput.grabFocus();
    }//GEN-LAST:event_btnSub1ActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        boolean flag=true;
        for(int i=0; i<text.length(); i++)
        {
            if(text.charAt(i) == '*' ||text.charAt(i) == '-' || text.charAt(i) == '/' || text.charAt(i) == '+')
            {JOptionPane.showMessageDialog(this, "Only 1 operator is allowed!");
            flag = false;
            break;
            }
        }
        if(flag == true)
            txtInput.setText(text+'*');
       
        txtInput.grabFocus();
    }//GEN-LAST:event_btnMulActionPerformed

    private void btndiv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiv1ActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        boolean flag=true;
        for(int i=0; i<text.length(); i++)
        {
            if(text.charAt(i) == '*' ||text.charAt(i) == '-' || text.charAt(i) == '/' || text.charAt(i) == '+')
            {JOptionPane.showMessageDialog(this, "Only 1 operator is allowed!");
            flag = false;
            break;
            }
        }
        if(flag == true)
            txtInput.setText(text+'/');
       
        txtInput.grabFocus();
    }//GEN-LAST:event_btndiv1ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        txtInput.setText(text+"8");
        txtInput.grabFocus();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        txtInput.setText(text+"9");
        txtInput.grabFocus();
    }//GEN-LAST:event_btn10ActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed
        // TODO add your handling code here:
        String text = txtInput.getText();
        String n1="",n2="";
        char opr=' ';
        int turn=0;
        for(int i=0; i<text.length(); i++)
        {
            if(text.charAt(i) == '+' || text.charAt(i) == '-' ||text.charAt(i) == '*' || text.charAt(i) == '/')
            {
               opr = text.charAt(i);
               turn = i;
            }
        }
        double num1,num2;
        n1 = text.substring(0, turn);
        n2 = text.substring(turn+1);
        if(n1.isEmpty())
        {
            txtInput.setText(n2);
            return;
        }
        else 
           num1 = Double.parseDouble(n1);  
        
        
        
        if(n2.isEmpty())
        {
            txtInput.setText(n1);
            return;
        }
        else
            num2 = Double.parseDouble(n2);
        
        
        
        
              
        
        if(opr == '+')
        {      
           double add= num1+num2;
          txtInput.setText(add+"");
           txtInput.grabFocus();
            
        } else if(opr == '-')
        {
            double add= num1-num2;
           txtInput.setText(add+"");
           txtInput.grabFocus();
            
        } else if(opr == '*')
        {
            double add= num1*num2;
           txtInput.setText(add+"");
           txtInput.grabFocus();
            
        }
         else if(opr == '/')
        {
            if(num2 == 0){
            JOptionPane.showMessageDialog(this, "Cant be divisible by 0");
            txtInput.setText("");
            txtInput.grabFocus();
            return;
            }
            
            
            double add= num1/num2;
           txtInput.setText(add+"");
           txtInput.grabFocus();
            
        }
        
        
    }//GEN-LAST:event_btnequalActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoffActionPerformed
        // TODO add your handling code here:
        turnOff();
    }//GEN-LAST:event_btnoffActionPerformed

    private void btnonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnonActionPerformed
        // TODO add your handling code here:
         turnOn();
         txtInput.setText("");
         txtInput.grabFocus();
         
    }//GEN-LAST:event_btnonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    public void turnOn()
    {
        txtInput.setEnabled(true);
        btn0.setEnabled(true);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn10.setEnabled(true);
        btndot.setEnabled(true);
        btnAdd.setEnabled(true);
        btnMul.setEnabled(true);
        btnSub1.setEnabled(true);
        btnc.setEnabled(true);
        btndiv.setEnabled(true);
        btnequal.setEnabled(true);
        btndiv1.setEnabled(true);
        btnoff.setEnabled(true);
        btnexit.setEnabled(true);
    }
    public void turnOff()
    {
        txtInput.setEnabled(false);
        btn0.setEnabled(false);
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn10.setEnabled(false);
        btndot.setEnabled(false);
        btnAdd.setEnabled(false);
        btnMul.setEnabled(false);
        btnSub1.setEnabled(false);
        btnc.setEnabled(false);
        btndiv.setEnabled(false);
        btnequal.setEnabled(false);
        btndiv1.setEnabled(false);
        btnoff.setEnabled(false);
        btnexit.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnSub1;
    private javax.swing.JButton btnc;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btndiv1;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnoff;
    private javax.swing.JButton btnon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
